version: '3.4'

services:
  oidc-provider-app:    
    image: i3market/oidc-provider-app
    container_name: oidc-provider-app
    restart: unless-stopped
    ports:
      - 3300:3300
    env_file:
      - .env.oidc
    networks:
      - oidc-net
      - reverse-proxy
    volumes:
      - ./volumes/misc:/app/misc
    depends_on:
      - oidc-provider-db

  oidc-provider-db:
    container_name: oidc-provider-db
    image: mongo:4-bionic
    restart: unless-stopped
    networks:
      - oidc-net
    env_file:
      - .env.oidc
    ports:
      - 27017:27017
    volumes:
      - oidc-mongo:/data/db
      - ./volumes/scripts:/data/scripts:ro
      - ./volumes/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: --quiet --setParameter logLevel=0

networks:
  oidc-net:
  reverse-proxy:
    external: true
volumes:
  oidc-mongo:
