version: '3.6'

services:
  oidc-provider-app:
    image: registry.gitlab.com/i3-market/code/wp3/t3.1-self-sovereign-identity-and-access-management/node-oidc-provider
    container_name: oidc-provider-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${HOST_BIND_IP-127.0.0.1}:$HOST_PORT:3000
    networks:
      - oidc-net
    volumes:
      - oidc-misc:/app/misc
    depends_on:
      - oidc-provider-db
  oidc-provider-db:
    container_name: oidc-provider-db
    image: mongo:4-bionic
    restart: unless-stopped
    networks:
      - oidc-net
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - oidc-mongo:/data/db
      - ./db/scripts:/data/scripts
      - ./db/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: --quiet --setParameter logLevel=0
networks:
  oidc-net:
volumes:
  oidc-mongo:
  oidc-misc:
