version: '3.6'

services:
  oidc-provider-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: i3market/oidc-provider-app
    container_name: oidc-provider-app
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - oidc-net
      - reverse-proxy
    volumes:
      - oidc-misc:/app/misc
    depends_on:
      - oidc-provider-db
  oidc-provider-db:
    container_name: oidc-provider-db
    image: mongo:4-bionic
    restart: unless-stopped
    networks:
      - oidc-net
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - oidc-mongo:/data/db
      - ./db/scripts:/data/scripts
      - ./db/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: --quiet --setParameter logLevel=0
networks:
  oidc-net:
  reverse-proxy:
    external: true
volumes:
  oidc-mongo:
  oidc-misc:
