openapi: '3.0.3'
info:
  description: The API of the i3Market OpenID Connect Provider. 
  version: 1.0.0
  title: i3-market OpenID Connect Provider API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

tags:
  - name: OIDC Core
    description: |
      The OpenID Connect Core 1.0 defines the core OpenID Connect functionality: authentication built on top of OAuth 2.0 and the use of Claims to communicate information about the End-User. It also describes the security and privacy considerations for using OpenID Connect.
    externalDocs:
      url: https://openid.net/specs/openid-connect-core-1_0.html
  - name: OIDC Discovery
    description: The OpenID Connect Discovery 1.0 specification defines a mechanism for an OpenID Connect Relying Party to discover the End-User's OpenID Provider and obtain information needed to interact with it, including its OAuth 2.0 endpoint locations.
    externalDocs:
      url: https://openid.net/specs/openid-connect-discovery-1_0.html
  - name: Developers
    description: Developers endpoint. Developers can log in to get a valid initial_access_token for regsitering new clients

servers:
- url: "{method}://{url}{contextPath}"
  description: The url of the running instance in the server
  variables:
    method:
      default: http
      description: http or https
    url:
      default: localhost:3300
      description: server url
    contextPath:      
      default: /release2
      description: context path

paths:
  /oidc/.well-known/openid-configuration:
    $ref: './paths/oidc/well-known-openid-configuration.yaml#/paths/~1.well-known~1openid-configuration'

  /oidc/jwks:
    $ref: './paths/oidc/jwks.yaml#/paths/~1jwks'

  /oidc/auth:
    $ref: "./paths/oidc/auth.yaml#/paths/~1auth"

  /oidc/token:
    $ref: "./paths/oidc/token.yaml#/paths/~1token"

  /developers/login:
    $ref: "./paths/developers/login.yaml#/paths/~1login"

  /oidc/reg:
    post:
      summary: Registering a new client.
      description: |
        Register a new client. You have to authenticate this API with a bearer JWT "initialAccessToken" retrieved with the API /developers/lgin
      tags:
        - Developers
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              grant_types: [ "authorization_code" ]
              token_endpoint_auth_method: "'none' // One of 'none' (PKCE required), 'client_secret_basic', 'client_secret_jwt', 'client_secret_post', 'private_key_jwt'"
              redirect_uris: ["https://client.example.org/callback", "https://client.example.org/callback2"]
              post_logout_redirect_uris: [ 'http://localhost:3001/oidc/logout/cb' ]
              client_name: "MyClientExample"
              id_token_signed_response_alg: "EdDSA"

      responses:
        "200":
          description: Rely party client account created
        "500":
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "schema/error.yaml#/Error"

components:
  securitySchemes:
    BasicAuth:
      $ref: "./security-schemes/basic.yaml#/basicAuth"    

    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT    
  
security:
  - bearerAuth: []     