openapi: '3.0.3'
info:
  description: The API of the i3Market OpenID Connect Provider.
  version: 0.9.0
  title: i3-market OpenID Connect Provider API
  contact:
    name: Fernando Román García, Juan Hernández Serrano
    email: fernando.roman@upc.edu

  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: http://localhost:3000/rp
    description: 'Development server'

tags:
  - name: OIDC Core
    description: |
      The OpenID Connect Core 1.0 defines the core OpenID Connect functionality: authentication built on top of OAuth 2.0 and the use of Claims to communicate information about the End-User. It also describes the security and privacy considerations for using OpenID Connect.
    externalDocs:
      url: https://openid.net/specs/openid-connect-core-1_0.html
  - name: OIDC Discovery
    description: The OpenID Connect Discovery 1.0 specification defines a mechanism for an OpenID Connect Relying Party to discover the End-User's OpenID Provider and obtain information needed to interact with it, including its OAuth 2.0 endpoint locations.
    externalDocs:
      url: https://openid.net/specs/openid-connect-discovery-1_0.html
  - name: RP
    description: Rely Party client managent endpoints, including login, registration, etc

paths:
  /register:
    post:
      summary: Register a new client
      operationId: rpCreate
      tags:
        - RP
      requestBody:
        description: Creation method
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "201":
          description: Rely party client account created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "../../schema/error.yaml#/Error"

components:
  schemas:
    RegisterRequest:
      title: RegisterRequest
      description: |
        Relying party registartion object
      type: object
      required:
        - clientId
        - clientSecret
        - redirectUris
      properties:
        clientId:
          type: string
          default: someid
        clientSecret:
          type: string
          default: gRbFEk3WWF
        tokenEndpointAuthMethod:
          type: string
          description: |
            Values supported are:
            - "none" (for PKCE)
            - "client_secret_basic"
            - "client_secret_jwt"
            - "client_secret_post"
            - "private_key_jwt"
          default: none
          enum:
          - none
          - client_secret_basic
          - client_secret_jwt
          - client_secret_post
          - private_key_jwt
        redirectUris:
          $ref: "#/components/schemas/UriArray"
        postLogoutRedirectUris:
          $ref: "#/components/schemas/UriArray"
    RegisterResponse:
      title: RegisterResponse
      description: |
        Relying party registartion response
      type: object
      required:
        - clientId
        - redirectUris
      properties:
        clientId:
          type: string
        redirectUris:
          $ref: "#/components/schemas/UriArray"
        postLogoutRedirectUris:
          $ref: "#/components/schemas/UriArray"
      additionalProperties: true

    UriArray:
      title: UriArray
      type: array
      items:
        type: string
        default: http://example.foo/some/path
        format: uri
