openapi: '3.0.3'
info:
  description: The API of the i3Market OpenID Connect Provider. 
  version: __VERSION__
  title: i3-market OpenID Connect Provider API

paths:
  /login:
    get:
      summary: Obtain a valid initial_access_token for registering a new client.
      description: |
        Obtain a valid initial_access_token for registering a new client. Use that token as a bearer authentication token with this endpoint to register a new client with a POST of a JSON to [/oidc/reg](/oidc/reg).
        
        Example POST:
        
        ```json
        {
          "grant_types": [ "authorization_code" ],
          "token_endpoint_auth_method": "client_secret_jwt",
          "redirect_uris":
            ["https://client.example.org/callback",
              "https://client.example.org/callback2"],
          "client_name": "My Example",
          "id_token_signed_response_alg": "EdDSA"
        }
        ```
        
        (TO BE INCLUDED IN THE SPEC UI, you can just test it with postman)
      tags:
        - Developers
      security:
        - BasicAuth: []
      responses:
        "200":
          description: Rely party client account created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InitialAccessToken"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "../../schema/error.yaml#/Error"

components:
  schemas:
    InitialAccessToken:
      title: InitialAccessToken
      description: |
        An initial access token that can be used to register a new client with a POST of a JSON to [/oidc/reg](/oidc/reg).
      type: object
      required:
        - initialAccessToken
      properties:
        initialAccessToken:
          type: string
          example: 'JmmRhudSc6VkVzvIQamP-pe5Zj4k7TR_oqe6uzIbiYW'

  securitySchemes:
    BasicAuth:
      $ref: "../../security-schemes/basic.yaml#/basicAuth"
