openapi: '3.0.3'
info:
  description: The API of the i3Market OpenID Connect Provider. 
  version: __VERSION__
  title: i3-market OpenID Connect Provider API

paths:
  /{credentialName}/{did}:
    get:
      tags: 
        - Credential
      summary: |
        Obtain a testing verifiable credential for either a consumer or a provider.
      description: |
        The **response is a QR code that should be rendered**. For testing just connect to this endpoint directly from a browser
      parameters:
        - in: path
          name: credentialName   # Note the name is the same as in the path
          required: true
          schema:
            type: string
            enum:
              - "consumer"
              - "provider" 
          description: |
            The name of the credential you want to obtain. Currently either "consumer" or "provider".
          example: "consumer"
        - in: path
          name: did
          required: true
          schema:
            type: string
          description: |
            The DID of the entity the credential will be issued to. You can check yours in uPort->Settings->uPort ID->DID (just click and it will be copied to the clipboard)
          example: did:ethr:0x27e87e7eea3336c2c3d6636234f60a4cbfc2d637
      security:
        - BasicAuth: []
      responses:
        "200":
          description: a QR code is sent and should be scanned with a mobile phone using uPort to initiate the credential issuing process. **For testing it is easier to just connect to this endpoint directly from a browser**
          
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "../schema/error.yaml#/Error"
components:
  securitySchemes:
    BasicAuth:
      $ref: "../security-schemes/basic.yaml#/basicAuth"