openapi: '3.0.3'
info:
  description: The API of the i3Market OpenID Connect Provider. 
  version: 0.9.0
  title: i3-market OpenID Connect Provider API
  contact:
    name: Fernando Román García, Juan Hernández Serrano
    email: fernando.roman@upc.edu

  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: /oidc
    description: Local testing server

tags:
  - name: OIDC Core
    description: |
      The OpenID Connect Core 1.0 defines the core OpenID Connect functionality: authentication built on top of OAuth 2.0 and the use of Claims to communicate information about the End-User. It also describes the security and privacy considerations for using OpenID Connect.
    externalDocs:
      url: https://openid.net/specs/openid-connect-core-1_0.html
  - name: OIDC Discovery
    description: The OpenID Connect Discovery 1.0 specification defines a mechanism for an OpenID Connect Relying Party to discover the End-User's OpenID Provider and obtain information needed to interact with it, including its OAuth 2.0 endpoint locations.
    externalDocs:
      url: https://openid.net/specs/openid-connect-discovery-1_0.html

paths:
  /.well-known/openid-configuration:
    $ref: './paths/well-known-openid-configuration.yaml#/paths/~1.well-known~1openid-configuration'
  
  /jwks:
    $ref: './paths/jwks.yaml#/paths/~1jwks'

  /auth:
    $ref: "./paths/auth.yaml#/paths/~1auth"

  /token:
    $ref: "./paths/token.yaml#/paths/~1token"

components:
  securitySchemes:
    ClientAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic